version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - keycloak_network
    restart: unless-stopped
    
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    hostname: keycloak
    container_name: keycloak
    environment:
        KC_HOSTNAME_STRICT_BACKCHANNEL: false
        KC_HTTP_ENABLED: true
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_HEALTH_ENABLED: true
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres/test_db
        KC_DB_USERNAME: admin
        KC_DB_PASSWORD: root
    ports:
        - "8180:8080"
    volumes:
        - ./keycloak/imports:/opt/keycloak/data/import
    command: 
        - start-dev
        - --import-realm
    networks:
      - keycloak_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  keycloak_network:
